name: Lodzplaza
favicon: null
layout_spectrum: 0.9922155
typography_spectrum: 0.3829787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdf9f6'
    - '#161419'
    - '#6b3329'
    - '#b36644'
    - '#fcbc2c'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
