name: Lodzplaza
favicon: null
layout_spectrum: 0.9922155
typography_spectrum: 0.3829787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9423292
  lightness: 0.9042553
  saturation: 0.8361702
  rhythmicContrast: 0.9082209
purpose: []
